/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.management.system;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author lenovo
 */
public class JFrame extends javax.swing.JFrame {
    static int i;
    double priceTacos = 20;
    double priceBurger = 25;
    double pricePizza1 = 30;
    double pricePizza2 = 30;
    double pricePizza3 = 20;
    double pricePizza4 = 25;
    double priceSandwich = 20;
    double priceSalade1 = 10;
    double priceSalade2 = 15;
    double priceSalade3 = 15;
    double priceSalade4 = 25;
    double priceSalade5 = 22;
    double priceBoisson = 10;
    double homeDelivery = 10;
    double mealCost=0, total=0, paiment, change;
    
    
    Item item = new Item();
    /**
     * Creates new form JFrame
     */
    public JFrame(String exit) {
        initComponents();
        btnRemove.setEnabled(false);
        btnClear.setEnabled(false);
        txtTotal.setEditable(false);
        txtCost.setEditable(false);
        txtChange.setEditable(false);
        i = 0;
    }
    public void start(){
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if (model.getRowCount() >= 0){
            btnTotal.setEnabled(true);
            btnClear.setEnabled(true);
            btnRemove.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCBTacos = new javax.swing.JCheckBox();
        jCBBurger = new javax.swing.JCheckBox();
        jCBPizza = new javax.swing.JCheckBox();
        jCBSandwich = new javax.swing.JCheckBox();
        jCBSalade = new javax.swing.JCheckBox();
        jCBBoisson = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuTacos = new javax.swing.JComboBox<>();
        menuBurger = new javax.swing.JComboBox<>();
        menuPizza = new javax.swing.JComboBox<>();
        menuSandwich = new javax.swing.JComboBox<>();
        menuSalade = new javax.swing.JComboBox<>();
        menuBoisson = new javax.swing.JComboBox<>();
        txtQteTacos = new javax.swing.JTextField();
        txtQteBurger = new javax.swing.JTextField();
        txtQtePizza = new javax.swing.JTextField();
        txtQteSandwich = new javax.swing.JTextField();
        txtQteSalade = new javax.swing.JTextField();
        txtQteBoisson = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        jCBDelivery = new javax.swing.JCheckBox();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPaiment = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btnAddTacos = new javax.swing.JButton();
        btnAddBurger = new javax.swing.JButton();
        btnAddPizza = new javax.swing.JButton();
        btnAddSandwich = new javax.swing.JButton();
        btnAddSalade = new javax.swing.JButton();
        btnAddBoisson = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Restaurant Management System");

        jCBTacos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBTacos.setText("Tacos");
        jCBTacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTacosActionPerformed(evt);
            }
        });

        jCBBurger.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBBurger.setText("Burger");
        jCBBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBurgerActionPerformed(evt);
            }
        });

        jCBPizza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBPizza.setText("Pizza");
        jCBPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPizzaActionPerformed(evt);
            }
        });

        jCBSandwich.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBSandwich.setText("Sandwich");
        jCBSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSandwichActionPerformed(evt);
            }
        });

        jCBSalade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBSalade.setText("Salade");
        jCBSalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSaladeActionPerformed(evt);
            }
        });

        jCBBoisson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBBoisson.setText("Boisson");
        jCBBoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBoissonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Menu");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Item");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Qte");

        menuTacos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tacos Viande hachée", "Tacos Poulet", "Tacos Charcuterie", "Tacos mixte" }));
        menuTacos.setEnabled(false);

        menuBurger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burger de viande", "Burger poisson", "Cheeseburger", "burger King" }));
        menuBurger.setEnabled(false);

        menuPizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pizza 4 frommages", "Pizza 4 saisons", "Pizza Viande hachée", "Pizza fruits de mer" }));
        menuPizza.setEnabled(false);

        menuSandwich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandwich Poulet", "Sandwich Mixte", "Sandwich Dinde", "Panini" }));
        menuSandwich.setEnabled(false);

        menuSalade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salade Marocaine", "Salade César", "Salade Niçoise", "Salade Royale", "Salade Variée" }));
        menuSalade.setEnabled(false);

        menuBoisson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CocaCola", "Poms", "Hawai", "Boisson énergétique", "Eau minérale 300ml", "Eau minérale 500ml" }));
        menuBoisson.setEnabled(false);

        txtQteTacos.setEnabled(false);
        txtQteTacos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQteTacosKeyTyped(evt);
            }
        });

        txtQteBurger.setEnabled(false);
        txtQteBurger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQteBurgerKeyTyped(evt);
            }
        });

        txtQtePizza.setEnabled(false);
        txtQtePizza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtePizzaKeyTyped(evt);
            }
        });

        txtQteSandwich.setEnabled(false);
        txtQteSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQteSandwichKeyTyped(evt);
            }
        });

        txtQteSalade.setEnabled(false);
        txtQteSalade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQteSaladeKeyTyped(evt);
            }
        });

        txtQteBoisson.setEnabled(false);
        txtQteBoisson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQteBoissonKeyTyped(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setEnabled(false);
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRemoveMouseReleased(evt);
            }
        });
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("Clear Table");
        btnClear.setEnabled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Meal Cost");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Total         ");

        jCBDelivery.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCBDelivery.setText("Home Delivery ");
        jCBDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDeliveryActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Client Paiment ");

        txtPaiment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPaimentKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Change          ");

        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(0, 0, 153));
        btnTotal.setText("Total");
        btnTotal.setEnabled(false);
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price per Unit", "Qte", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMousePressed(evt);
            }
        });
        jTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTablePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        btnAddTacos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddTacos.setText("Add");
        btnAddTacos.setEnabled(false);
        btnAddTacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTacosActionPerformed(evt);
            }
        });

        btnAddBurger.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddBurger.setText("Add");
        btnAddBurger.setEnabled(false);
        btnAddBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBurgerActionPerformed(evt);
            }
        });

        btnAddPizza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddPizza.setText("Add");
        btnAddPizza.setEnabled(false);
        btnAddPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPizzaActionPerformed(evt);
            }
        });

        btnAddSandwich.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddSandwich.setText("Add");
        btnAddSandwich.setEnabled(false);
        btnAddSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSandwichActionPerformed(evt);
            }
        });

        btnAddSalade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddSalade.setText("Add");
        btnAddSalade.setEnabled(false);
        btnAddSalade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaladeActionPerformed(evt);
            }
        });

        btnAddBoisson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddBoisson.setText("Add");
        btnAddBoisson.setEnabled(false);
        btnAddBoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBoissonActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(102, 0, 51));
        jButton10.setText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 51));
        jButton11.setText("Reset");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPaiment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBSalade, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuSalade, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQteSalade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddSalade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQteSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddSandwich))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQteBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddBurger))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQtePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddPizza))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQteTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddTacos)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCBDelivery)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQteBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddBoisson)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(btnRemove)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClear)
                                        .addGap(53, 53, 53))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(159, 159, 159))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCBTacos)
                                            .addComponent(menuTacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQteTacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddTacos))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCBBurger)
                                            .addComponent(menuBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQteBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddBurger))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtQtePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddPizza)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(menuPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCBPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCBSandwich)
                                    .addComponent(menuSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQteSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddSandwich))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCBSalade)
                                    .addComponent(menuSalade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQteSalade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddSalade)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBBoisson)
                            .addComponent(menuBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQteBoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove)
                            .addComponent(btnClear)
                            .addComponent(btnAddBoisson))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBDelivery)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTacosActionPerformed
        if(jCBTacos.isSelected()){
            menuTacos.setEnabled(true);
            txtQteTacos.setEnabled(true);
            btnAddTacos.setEnabled(true);
            txtQteTacos.requestFocus();
            txtQteTacos.setText("1");
        }else {
            menuTacos.setEnabled(false);
            txtQteTacos.setEnabled(false);
            btnAddTacos.setEnabled(false);
            txtQteTacos.setText("");
        }
    }//GEN-LAST:event_jCBTacosActionPerformed

    private void jCBBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBurgerActionPerformed
        if(jCBBurger.isSelected()){
            menuBurger.setEnabled(true);
            txtQteBurger.setEnabled(true);
            btnAddBurger.setEnabled(true);
            txtQteBurger.requestFocus();
            txtQteBurger.setText("1");
        } else {
            menuBurger.setEnabled(false);
            txtQteBurger.setEnabled(false);
            btnAddBurger.setEnabled(false);
            txtQteBurger.setText("");
        }
    }//GEN-LAST:event_jCBBurgerActionPerformed

    private void jCBPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPizzaActionPerformed
        if(jCBPizza.isSelected()){
            menuPizza.setEnabled(true);
            txtQtePizza.setEnabled(true);
            btnAddPizza.setEnabled(true);
            txtQtePizza.requestFocus();
            txtQtePizza.setText("1");
        }else {
            menuPizza.setEnabled(false);
            txtQtePizza.setEnabled(false);
            btnAddPizza.setEnabled(false);
            txtQtePizza.setText("");
        }
    }//GEN-LAST:event_jCBPizzaActionPerformed

    private void jCBSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSandwichActionPerformed
        if(jCBSandwich.isSelected()){
            menuSandwich.setEnabled(true);
            txtQteSandwich.setEnabled(true);
            btnAddSandwich.setEnabled(true);
            txtQteSandwich.requestFocus();
            txtQteSandwich.setText("1");
        }
        else {
            menuSandwich.setEnabled(false);
            txtQteSandwich.setEnabled(false);
            btnAddSandwich.setEnabled(false);
            txtQteSandwich.setText("");
        }
    }//GEN-LAST:event_jCBSandwichActionPerformed

    private void jCBSaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSaladeActionPerformed
        if(jCBSalade.isSelected()){
            menuSalade.setEnabled(true);
            txtQteSalade.setEnabled(true);
            btnAddSalade.setEnabled(true);
            txtQteSalade.requestFocus();
            txtQteSalade.setText("1");
        }else {
            menuSalade.setEnabled(false);
            txtQteSalade.setEnabled(false);
            btnAddSalade.setEnabled(false);
            txtQteSalade.setText("");
        }
    }//GEN-LAST:event_jCBSaladeActionPerformed

    private void jCBBoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBoissonActionPerformed
        if(jCBBoisson.isSelected()){
            menuBoisson.setEnabled(true);
            txtQteBoisson.setEnabled(true);
            btnAddBoisson.setEnabled(true);
            txtQteBoisson.requestFocus();
            txtQteBoisson.setText("1");
        }else {
            menuBoisson.setEnabled(false);
            txtQteBoisson.setEnabled(false);
            btnAddBoisson.setEnabled(false);
            txtQteBoisson.setText("");
        }
    }//GEN-LAST:event_jCBBoissonActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        while (model.getRowCount() > 0){
            for (int j=0 ; j < model.getRowCount(); j++){
                model.removeRow(j);
            }
            i=0;
        }
        jCBTacos.setSelected(false);
        jCBBurger.setSelected(false);
        jCBPizza.setSelected(false);
        jCBSandwich.setSelected(false);
        jCBSalade.setSelected(false);
        jCBBoisson.setSelected(false);
        jCBDelivery.setSelected(false);
        menuTacos.setEnabled(false);
            txtQteTacos.setEnabled(false);
            btnAddTacos.setEnabled(false);
            txtQteTacos.setText("");
        menuBurger.setEnabled(false);
            txtQteBurger.setEnabled(false);
            btnAddBurger.setEnabled(false);
            txtQteBurger.setText("");
        menuPizza.setEnabled(false);
            txtQtePizza.setEnabled(false);
            btnAddPizza.setEnabled(false);
            txtQtePizza.setText("");
        menuSandwich.setEnabled(false);
            txtQteSandwich.setEnabled(false);
            btnAddSandwich.setEnabled(false);
            txtQteSandwich.setText("");
        menuSalade.setEnabled(false);
            txtQteSalade.setEnabled(false);
            btnAddSalade.setEnabled(false);
            txtQteSalade.setText("");
        menuBoisson.setEnabled(false);
            txtQteBoisson.setEnabled(false);
            btnAddBoisson.setEnabled(false);
            txtQteBoisson.setText("");
        btnRemove.setEnabled(false);
        btnClear.setEnabled(false);
        mealCost = 0;
        total = 0;
    }//GEN-LAST:event_btnClearActionPerformed

    private void jCBDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBDeliveryActionPerformed
    private JFrame frame;
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "You sure want to exit!", "Exit Alert", 
                    JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jCBTacos.setSelected(false);
        jCBBurger.setSelected(false);
        jCBPizza.setSelected(false);
        jCBSandwich.setSelected(false);
        jCBSalade.setSelected(false);
        jCBBoisson.setSelected(false);
        jCBDelivery.setSelected(false);
        txtQteTacos.setText(null);
        txtQteBurger.setText(null);
        txtQtePizza.setText(null);
        txtQteSandwich.setText(null);
        txtQteSalade.setText(null);
        txtQteBoisson.setText(null);
        txtCost.setText(null);
        txtTotal.setText(null);
        txtPaiment.setText(null);
        txtChange.setText(null);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        while (model.getRowCount() > 0){
            for (int j=0 ; j < model.getRowCount(); j++){
                model.removeRow(j);
            }
            i=0;
        }
        menuTacos.setEnabled(false);
            txtQteTacos.setEnabled(false);
            btnAddTacos.setEnabled(false);
            txtQteTacos.setText("");
        menuBurger.setEnabled(false);
            txtQteBurger.setEnabled(false);
            btnAddBurger.setEnabled(false);
            txtQteBurger.setText("");
        menuPizza.setEnabled(false);
            txtQtePizza.setEnabled(false);
            btnAddPizza.setEnabled(false);
            txtQtePizza.setText("");
        menuSandwich.setEnabled(false);
            txtQteSandwich.setEnabled(false);
            btnAddSandwich.setEnabled(false);
            txtQteSandwich.setText("");
        menuSalade.setEnabled(false);
            txtQteSalade.setEnabled(false);
            btnAddSalade.setEnabled(false);
            txtQteSalade.setText("");
        menuBoisson.setEnabled(false);
            txtQteBoisson.setEnabled(false);
            btnAddBoisson.setEnabled(false);
            txtQteBoisson.setText("");
        btnRemove.setEnabled(false);
        btnClear.setEnabled(false);
        mealCost = 0;
        total = 0;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtQteTacosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQteTacosKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQteTacosKeyTyped

    private void txtQteBurgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQteBurgerKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQteBurgerKeyTyped

    private void txtQtePizzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtePizzaKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQtePizzaKeyTyped

    private void txtQteSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQteSandwichKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQteSandwichKeyTyped

    private void txtQteSaladeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQteSaladeKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQteSaladeKeyTyped

    private void txtQteBoissonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQteBoissonKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtQteBoissonKeyTyped

    private void txtPaimentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaimentKeyTyped
        char n = evt.getKeyChar();
        if(!(Character.isDigit(n)) || (n == KeyEvent.VK_BACK_SPACE) || (n == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPaimentKeyTyped

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        /*txtTotal.setEnabled(true);
        txtCost.setEnabled(true);
        getTotal();
        txtCost.setText(Double.toString(mealCost));
        txtTotal.setText(Double.toString(total));*/
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnAddTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTacosActionPerformed
        item.itemName=menuTacos.getSelectedItem().toString();
        item.pricePerUnit=priceTacos;
        item.qte=Double.parseDouble(txtQteTacos.getText());
        item.total=item.price();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{item.itemName, item.pricePerUnit, item.qte, item.total});
    }//GEN-LAST:event_btnAddTacosActionPerformed

    private void btnAddBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBurgerActionPerformed
        item.itemName=menuBurger.getSelectedItem().toString();
        item.pricePerUnit=priceBurger;
        item.qte=Double.parseDouble(txtQteBurger.getText());
        item.total=item.price();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{item.itemName, item.pricePerUnit, item.qte, item.total});
    }//GEN-LAST:event_btnAddBurgerActionPerformed

    private void btnAddSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSandwichActionPerformed
        item.itemName=menuSandwich.getSelectedItem().toString();
        item.pricePerUnit=priceSandwich;
        item.qte=Double.parseDouble(txtQteSandwich.getText());
        item.total=item.price();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{item.itemName, item.pricePerUnit, item.qte, item.total});
    }//GEN-LAST:event_btnAddSandwichActionPerformed

    private void btnAddBoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBoissonActionPerformed
        item.itemName=menuBoisson.getSelectedItem().toString();
        item.pricePerUnit=priceBoisson;
        item.qte=Double.parseDouble(txtQteBoisson.getText());
        item.total=item.price();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{item.itemName, item.pricePerUnit, item.qte, item.total});
    }//GEN-LAST:event_btnAddBoissonActionPerformed

    private void btnAddPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPizzaActionPerformed
        item.itemName=menuPizza.getSelectedItem().toString();
        switch(item.itemName){
            case "Pizza 4 frommages" :item.pricePerUnit=pricePizza1;
            case "Pizza 4 saisons" :item.pricePerUnit=pricePizza2;
            case "Pizza Viande hachée" :item.pricePerUnit=pricePizza3;
            case "Pizza fruits de mer" :item.pricePerUnit=pricePizza4;
        }
        item.qte=Double.parseDouble(txtQtePizza.getText());
        item.total=item.price();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{item.itemName, item.pricePerUnit, item.qte, item.total});
    }//GEN-LAST:event_btnAddPizzaActionPerformed

    private void btnAddSaladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaladeActionPerformed
        item.itemName=menuSalade.getSelectedItem().toString();
        switch(item.itemName){
            case "Salade Marocaine" :item.pricePerUnit=priceSalade1;
            case "Salade César" :item.pricePerUnit=priceSalade2;
            case "Salade Niçoise" :item.pricePerUnit=priceSalade3;
            case "Salade Royale" :item.pricePerUnit=priceSalade4;
            case "Salade Variée" :item.pricePerUnit=priceSalade5;
        }
        item.qte=Double.parseDouble(txtQteSalade.getText());
        item.total=item.price();
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{item.itemName, item.pricePerUnit, item.qte, item.total});
    }//GEN-LAST:event_btnAddSaladeActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow() != -1) {
            // remove selected row from the model
            model.removeRow(jTable.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMousePressed
        if(jTable.getSelectedRow() != -1) {
            btnRemove.setEnabled(true);
            btnClear.setEnabled(true);
        }
    }//GEN-LAST:event_jTableMousePressed

    private void btnRemoveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseReleased
        btnRemove.setEnabled(false);
    }//GEN-LAST:event_btnRemoveMouseReleased

    private void jTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTablePropertyChange
        start();
        getTotal();
    }//GEN-LAST:event_jTablePropertyChange
    
    public void getTotal(){
        TableModel tm = jTable.getModel();
        for (int i = 0; i < tm.getRowCount(); i++) {
            int j = tm.getColumnCount();
            Object o = tm.getValueAt(i, j);
            double price = (Double)o;
            mealCost += price; 
        }
        if(jCBDelivery.isSelected()){
            total = mealCost + 10;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame("Exit").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBoisson;
    private javax.swing.JButton btnAddBurger;
    private javax.swing.JButton btnAddPizza;
    private javax.swing.JButton btnAddSalade;
    private javax.swing.JButton btnAddSandwich;
    private javax.swing.JButton btnAddTacos;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JCheckBox jCBBoisson;
    private javax.swing.JCheckBox jCBBurger;
    private javax.swing.JCheckBox jCBDelivery;
    private javax.swing.JCheckBox jCBPizza;
    private javax.swing.JCheckBox jCBSalade;
    private javax.swing.JCheckBox jCBSandwich;
    private javax.swing.JCheckBox jCBTacos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JComboBox<String> menuBoisson;
    private javax.swing.JComboBox<String> menuBurger;
    private javax.swing.JComboBox<String> menuPizza;
    private javax.swing.JComboBox<String> menuSalade;
    private javax.swing.JComboBox<String> menuSandwich;
    private javax.swing.JComboBox<String> menuTacos;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtPaiment;
    private javax.swing.JTextField txtQteBoisson;
    private javax.swing.JTextField txtQteBurger;
    private javax.swing.JTextField txtQtePizza;
    private javax.swing.JTextField txtQteSalade;
    private javax.swing.JTextField txtQteSandwich;
    private javax.swing.JTextField txtQteTacos;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}

